recipe: default.v1
language: "fr"

pipeline:
  - name: SpacyNLP
    model: fr_dep_news_trf
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: True
    tensorboard_log_directory: ".tensorboard/3intents-0-e-trf"
    tensorboard_log_level: "epoch"
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: True
    tensorboard_log_directory: ".tensorboard/3intents-0-e-trf"
    tensorboard_log_level: "epoch"
